apiVersion: apps/v1
kind: Deployment
metadata:
  name: fault-tolerant-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fault-app
  template:
    metadata:
      labels:
        app: fault-app
    spec:
      containers:
      - name: app
        image: tchalimcanonical/tchalim-canonical-distributed:v1
        ports:
        - containerPort: 8000