apiVersion: v1
kind: Service
metadata:
  name: fault-service
spec:
  selector:
    app: fault-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      NodePort: 32000
  type: NodePort