apiVersion: v1
kind: Pod
metadata:
  name: fault-tolerant-api
  namespace: fault-tolerant
  labels:
    app.kubernetes.io/name: fault-tolerant
    app.kubernetes.io/component: backend
    app.kubernates.io/instance: fault-tolerant-api
spec:
  imagePullSecrets:
      - name: dockerhub-secret
  containers:
  - name: fault-tolerant
    image: tchalimcanonical/tchalim-canonical-distributed:v4
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "300Mi"
        cpu: "1000m"
    ports:
      - containerPort: 8000
